name: Fortran CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        gcc_v: [7, 8, 9, 10] # Version of GFortran we want to use.
    env:
      FC: gfortran-${{ matrix.gcc_v }}
      GCC_V: ${{ matrix.gcc_v }}    

    steps:
    - uses: actions/checkout@v2

    # Debugging session
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
        
    - name: vtest
      run: |
          gfortran --version
          $FC --version
      
    - name: make
      run: |
        cd SourceCode
        make

